version: 0.1

logging:
  level: 'debug'
  formatter: 'text'
  fields:
    userfield1: 'value'

http:
  addr: ':9181'
  host: 'localhost'
  cors:
    origins: ['*']
    methods: ['*']
    headers: ['*']
    debug: false

containers: 'embedded'

storage: 'memory'
