version: 1.0

logging:
  level: 'debug'
  formatter: 'text'

http:
  enabled: true
  addr: ':9181'
  host: 'localhost'
  cors:
    origins: ['*']
    methods: ['*']
    headers: ['*']
    debug: false

containers: 'embedded'

storage: 'inmemory'
